### ISSUE TITLE
refreshing the config screen doesn't preserve its selection

### ISSUE THREAD

**Issue by rminchev1** [rndsolutions/hawkcd#170]
**Steps**

Create a pipeline
Navigate to a certain task
Refresh the page:

**Result**

![image](https://cloud.githubusercontent.com/assets/1092422/17948547/ed70323c-6a59-11e6-9205-28da46965bd9.png)

**Expect Result**
The page should preserve my selection/state

**Comment by monitobeko** [comment]
This should be fixed in the latest master. Please update and try reproducing the bug again.
