### ISSUE TITLE
Run management screen has no UI style for selected stage 

### ISSUE THREAD

**Issue by SlaviDimitrov** [rndsolutions/hawkcd#235]
1. Go to management screen for pipeline with multiple stages 
2. Click on the header of one of the stages

**Actual**
The state has no UI indication to let the user know the stage is actually selected

**Expected**
The stage should indicate its selected state

**Comment by SlaviDimitrov** [comment]
As general suggestion for representing the state of each stage, we may consider coloring the header for each state. This way user can get a better understanding of the state at a glance.

**Comment by SlaviDimitrov** [comment]
Another aspect is the default selected item. 

When the run management is open for the first time it makes sense the last executed stage and its last executed job to be selected by default.

When user clicks on the header of specific stage it may be a good idea to select last the first or the last executed job.

**Comment by rminchev1** [comment]
Here's the latest requirements about this item: 

- Upon visiting the screen,  Fist Stage |  First job should be selected
- Keep the "active/running" join into the view
- Collapse "Pipeline run Info " panel by default  
- Implement "full screen mode" of the console
