### ISSUE TITLE
Operator in every permission scope can not cancel pipeline execution

### ISSUE THREAD

**Issue by birkoff88** [rndsolutions/hawkcd#256]
Steps to reproduce:
Log in as admin.
Change user permissions to Any  - Operator - Any

**Expected**
Any user with operator privilege to run a pipeline should be able to also cancel execution.

**Actual**
After pipeline execution is started, the user is not authorized to cancel execution.
Notification: Unauthorized

**Comment by rminchev1** [comment]
good catch @birkoff88 !
