### ISSUE TITLE
Edit task in job definition does not reload old data on cancel

### ISSUE THREAD

**Issue by hpslavov** [rndsolutions/hawkcd#261]
**Steps to reproduce:**
1.Go to pipeline config.
2.Select stage.
3.Select job.
4.Click edit task > change some value in the definition > click Cancel or Close.

**Expected result:**
The old definition should not be changed.

**Actual result:**
UI is not reloading old definition data.

**Comment by monitobeko** [comment]
Issue was fixed in #301
