### ISSUE TITLE
Creating a user from the admin screen adds to records on the UI and then the user can't login anymore

### ISSUE THREAD

**Issue by rminchev1** [rndsolutions/hawkcd#283]
**Steps to reproduce**

Press the "Aad" button for a new user 
Enter the details
Press the Tab button to move the focus to the save button 
Hit enter button

**Result:**
Two records are shown in the UI 
The user can't login with the created account

**Comment by VladislavNikolov** [comment]
Could not recreate bug, closing the issue until it reappears in some form.
