### ISSUE TITLE
Fix adding material to newly created pipeline.

### ISSUE THREAD

**Issue by birkoff88** [rndsolutions/hawkcd#308]
Steps to reproduce:

1. Log in as Admin
2. Go to Pipeline screen and click "add".
3. Enter Pipeline name and select "CONTINUE".
4. Select "existing material" checkbox and click on "CONTINUE".

**ACTUAL**
The user can continue without choosing existing material definition.

**EXPECTED** 
The user should not be able continue without choosing existing material definition.

**Comment by birkoff88** [comment]
@monitobeko fix option to go back and change pipeline definition name, when already clicked "Existing Material" radio button.

**Comment by VladislavNikolov** [comment]
@birkoff88 @monitobeko the issue should be fixed now, please review.
