### ISSUE TITLE
Editing Git URL on Materials with invalid input, breaks record in the DB. Shows blank value on the UI.

### ISSUE THREAD

**Issue by birkoff88** [rndsolutions/hawkcd#309]
Steps to reproduce: 

1. Login
2. Go to Admin screen and select 'Materials'.
3. Select 'EDIT' on existing material definition.
3. Enter invalid input in "Git Url "
4. Select OK

**ACTUAL**
![ujast](https://cloud.githubusercontent.com/assets/8957606/18663822/c56520e8-7f28-11e6-8431-945875c2106c.png) 

**EXPECTED**
The user should not be able to proceed if Git URL is invalid.

**Comment by VladislavNikolov** [comment]
Validation would not allow invalid input to be entered.
