### ISSUE TITLE
PipelineGroups validation.

### ISSUE THREAD

**Issue by birkoff88** [rndsolutions/hawkcd#324]
bug 1:

Sometimes (usually the first time) user can add empty PipelineGroup name by hitting enter. 
![invalidname](https://cloud.githubusercontent.com/assets/8957606/18982188/c579478c-86ec-11e6-9535-50c114a30518.png)

bug 2:

Entering invalid input ( ;' space /.@!) to new PipelineGroup name  by hitting enter causes NullPointerException on the Server console, shows empty red notification on the UI.
![invalidinput](https://cloud.githubusercontent.com/assets/8957606/18982303/c905ca96-86ed-11e6-9864-aa0877a5f35c.png)

**Comment by VladislavNikolov** [comment]
Issue related to #335
