### ISSUE TITLE
Unassigning Pipelines to PipelineGroups 

### ISSUE THREAD

**Issue by birkoff88** [rndsolutions/hawkcd#325]
Steps to reproduce: 
1.Login as Admin.
2.Go to PipelineGroups Admin screen. 
3. Mark **the last** pipeline in the row for unassigning and unassigin it.

**ACTUAL**
unassigning button is still active and selecting it will cause IllegalStateException.
![unassignpipeline](https://cloud.githubusercontent.com/assets/8957606/18982647/6342eb5a-86f0-11e6-9fae-52422f72e320.png)

![unassignpipeline2](https://cloud.githubusercontent.com/assets/8957606/18982665/89f64a8a-86f0-11e6-950d-281b755f3814.png)

![illegalstateexception](https://cloud.githubusercontent.com/assets/8957606/18982675/964f05ce-86f0-11e6-8308-687f6caa456d.png)

**Comment by monitobeko** [comment]
Issue similar to #274
