### ISSUE TITLE
UserGroups validation.

### ISSUE THREAD

**Issue by birkoff88** [rndsolutions/hawkcd#329]
Steps to reproduce

1. Login as Admin.
2. Go to Admin screen, UserGroups tab.
3. Select +Add, enter invalid key characters (;'!@#$%#) and hit 'Enter'

**ACTUAL**
![usergroups](https://cloud.githubusercontent.com/assets/8957606/18983422/4683c516-86f5-11e6-8a99-6b623836b23a.png)

**EXPECTED**
User should not be able to submit invalid input.

**Comment by VladislavNikolov** [comment]
Issue related to #335
