### ISSUE TITLE
Run Management Screen issues

### ISSUE THREAD

**Issue by rminchev1** [rndsolutions/hawkcd#355]
The Stage should has only 2 buttons: 

Play/Continue - **enabled** only when the stage it belongs to is "paused", pressing it, the pipeline can be continued, otherwise disabled
Stop/Cancel - enabled only when the stage it belongs to is in running status, otherwise is disabled

![image](https://cloud.githubusercontent.com/assets/1092422/19053744/dad9d648-89c4-11e6-8688-73ad260c2a7c.png)

**Comment by monitobeko** [comment]
Issue related to #357
