### ISSUE TITLE
firefox pipeline view misalignment 

### ISSUE THREAD

**Issue by rminchev1** [rndsolutions/hawkcd#379]
![image](https://cloud.githubusercontent.com/assets/1092422/19266954/bdcfe2c2-8fb4-11e6-9af4-9065ec8828d7.png)

**Comment by rminchev1** [comment]
removing relative positioning seems to fix the problem:

![image](https://cloud.githubusercontent.com/assets/1092422/19267018/0f13499e-8fb5-11e6-9931-2ac528f8bcc1.png)

**Comment by monitobeko** [comment]
@rminchev1 Could you please test this issue again, as I was not able to test it under Firefox.

**Comment by monitobeko** [comment]
Update: I managed to test it on Firefox and it seems to be working properly now.
